substitutions:
  node_name: gree # Use a unique name.
  node_id: Gree_ac    # Use a unique id.
  friendly_node_name: "Gree AC"
  deviceid: gree
  devicename: Kitchen

esphome:
  name: gree
  friendly_name: "Gree AC"

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: "[insert yours]"

ota:
  - platform: esphome
    password: "[insert yours]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gree Fallback Hotspot"
    password: "[insert yours]"

captive_portal:

# Enable logging
logger:
  baud_rate: 0 # disable LOG output on UART as UART is used for Sinclair AC unit
  level: VERBOSE

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 4800
  parity: EVEN

# Note: For BLE ATC sensor support with built-in listener, you need ESP32.
# Uncomment the following section if using ESP32 instead of ESP8266:
# esp32_ble_tracker:
#   scan_parameters:
#     active: false

time:
  - platform: sntp

external_components:
  - source: github://gekkehenkie11/esphome_gree_ac
    components: [sinclair_ac]
    refresh: 0s

climate:
  - platform: sinclair_ac
    name: ${devicename}
    horizontal_swing_select:
      name: ${devicename} Horizontal Swing Mode
    vertical_swing_select:
      name: ${devicename} Vertical Swing Mode
    display_select:
      name: ${devicename} Display Mode
    display_unit_select:
      name: ${devicename} Display Unit
    temp_source_select:
      name: ${devicename} Temperature Source
    plasma_switch:
      name: ${devicename} Plasma
    beeper_switch:
      name: ${devicename} Beeper      
    sleep_switch:
      name: ${devicename} Sleep
    xfan_switch:
      name: ${devicename} X-fan
    save_switch:
      name: ${devicename} Save/8 Heat
    atc_mac_address_text:
      name: ${devicename} ATC MAC Address
      mode: text
    ac_indoor_temp_sensor:
      name: ${devicename} AC Indoor Temperature
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      device_class: temperature
      state_class: measurement
    atc_room_temp_sensor:
      name: ${devicename} ATC Room Temperature
      unit_of_measurement: "°C"
      accuracy_decimals: 2
      device_class: temperature
      state_class: measurement
    atc_room_humidity_sensor:
      name: ${devicename} ATC Room Humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1
      device_class: humidity
      state_class: measurement
    atc_battery_sensor:
      name: ${devicename} ATC Battery
      unit_of_measurement: "%"
      accuracy_decimals: 0
      device_class: battery
      state_class: measurement
    
